DROP TABLE IF EXISTS [EVENT_KATEGORI];
DROP TABLE IF EXISTS [KATEGORI];
DROP TABLE IF EXISTS [SALGS_TAL]; 
DROP TABLE IF EXISTS [BILLET_TYPE];
DROP TABLE IF EXISTS [AFVIKLING];
DROP TABLE IF EXISTS [SAL];
DROP TABLE IF EXISTS [EVENT];
DROP TABLE IF EXISTS [UNDERSKUDS_GODTGØRELSE];

CREATE TABLE [UNDERSKUDS_GODTGØRELSE](
	[ReturProcent]		FLOAT(24)					NOT NULL,
	[UdløbsDato]		DATETIME2					NOT NULL,
	CONSTRAINT			[UNDERSKUDSGODTGØRELSE_PK]	PRIMARY KEY ([UdløbsDato])
)

CREATE TABLE [EVENT](
	[EventNavn]					NVARCHAR(200)				NOT NULL,
	[Markedsføring]				MONEY						NOT NULL,
	[Koda]						FLOAT(24)					NOT NULL,
	[Garantisum]				MONEY						NOT NULL,
	[ArtistSplit]				FLOAT(24)					NOT NULL,
	[VariableOmkostninger]		MONEY						NOT NULL,
	[OmkostningerNote]			NVARCHAR(400)				NOT NULL,
	[VariableIndtægter]			MONEY						NOT NULL,
	[IndtægterNote]				NVARCHAR(400)				NOT NULL,
	[UnderskudsGodtgørelse]		DATETIME2					NOT NULL,
	[EventId]					INT							IDENTITY (1,1)

	CONSTRAINT					[EVENT_PK]					PRIMARY KEY ([EventId]),
	CONSTRAINT					[UNDERSKUDSGODTGØRELSE_FK]	FOREIGN KEY ([UnderskudsGodtgørelse])
								REFERENCES [UNDERSKUDS_GODTGØRELSE] (UdløbsDato)
)

CREATE TABLE [SAL](
	[SalId]				INT					IDENTITY (1,1),
	[SalNavn]			NVARCHAR(100)		NOT NULL UNIQUE,
	[Leje]				MONEY				NOT NULL,
	[Kapacitet]			INT					NOT NULL,
	CONSTRAINT			[SAL_PK]			PRIMARY KEY ([SalId])
)

CREATE TABLE [AFVIKLING](
	[DatoId]			INT					IDENTITY (1,1),
	[Dato]				DATETIME2			NOT NULL,
	[Event]				INT					NOT NULL,
	[Sal]				INT					NOT NULL,
	CONSTRAINT			[AFVIKLING_PK]		PRIMARY KEY ([DatoId]),
	CONSTRAINT			[SAL_FK]			FOREIGN KEY ([Sal])
						REFERENCES [SAL] (SalId),
	CONSTRAINT			[AFVIKLING_EVENT_FK]FOREIGN KEY ([Event])
						REFERENCES [EVENT] (EventId)
)

CREATE TABLE [BILLET_TYPE](
	[BilletTypeId]		INT					IDENTITY (1,1),
	[Udbud]				INT					NOT NULL,
	[Pris]				MONEY				NOT NULL,
	[Afvikling]			INT					NOT NULL,
	CONSTRAINT			[BILLET_TYPE_PK]	PRIMARY KEY ([BilletTypeId]),
	CONSTRAINT			[AFVIKLING_FK]		FOREIGN KEY ([Afvikling])
						REFERENCES [AFVIKLING] (DatoId)
)

CREATE TABLE [SALGS_TAL](
	[SalgsTalId]		INT					IDENTITY (1,1),
	[Bevægelse]			INT					NOT NULL,
	[BilletType]		INT					NOT NULL,
	[SalgsDato]			DATETIME2			NOT NULL,
	CONSTRAINT			[SALGS_TAL_PK]		PRIMARY KEY ([SalgsTalId]),
	CONSTRAINT			[BILLT_TYPE_FK]		FOREIGN KEY ([BilletType])
						REFERENCES [BILLET_TYPE] (BilletTypeId)
)

CREATE TABLE [KATEGORI](
	[KategoriId]		INT				IDENTITY (1,1),
	[KategoriNavn]		VARCHAR(100)	NOT NULL UNIQUE,
	CONSTRAINT			[KATEGORI_PK]	PRIMARY KEY ([KategoriId])
)

CREATE TABLE [EVENT_KATEGORI](
	[Event]				INT						NOT NULL,
	[Kategori]			INT						NOT NULL,
	CONSTRAINT			[EVENT_KATEGORI_PK]		PRIMARY KEY ([Event],[Kategori]),
	CONSTRAINT			[EVENT_FK]				FOREIGN KEY ([Event])
						REFERENCES [EVENT] (EventId),
	CONSTRAINT			[KATEGORI_FK]			FOREIGN KEY ([Kategori])
						REFERENCES [KATEGORI] (KategoriId)
)